Handle empty last_error strings. (#40)
If the `last_error` of a failed Que job is an empty string (which can
happen on older versions of Que that do not include the stack trace in
the last error) the `Failed` jobs page blows up with an exception, as
`format_error` assumes that a non-nil value will not be a blank string:

```
NoMethodError - undefined method `length' for nil:NilClass:
        que-web/lib/que/web.rb:196:in `truncate'
        que-web/lib/que/web.rb:188:in `format_error'
        que-web/web/views/failing.erb:35:in `block (2 levels) in singleton class'
        que-web/web/views/failing.erb:25:in `each'
        .
        .
```